name: Snakemake Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Snakemake & YAML
      run: |
        python -m pip install --upgrade pip
        pip install "snakemake" "pulp<2.8.0" "pyyaml"
        
    - name: Validate Workflow (Dry-run)
      run: |
                  touch ci_r1.fq.gz ci_r2.fq.gz
                  snakemake -n
